### PR TITLE
Add Go lint version locking

### PR DESCRIPTION
**Pull request by pointlessone**
This change allows us control the version of Go lint used in this engine as well as explicitly update the engine and trigger new image build.

### CODE REVIEW

**Comment by pointlessone** [comment]
@wfleming Thanks! Could you please handle the merge and the rest?

**Comment by tmaczukin** [comment]
@wfleming @ABaldwinHunter Are there any plans to merge this?

**Comment by tmaczukin** [comment]
However, the code present here is unable to be compiled right now, because of the `github.com/golang/lint` import definition. I've prepared #23 on top of this PR to address this problem and add few other minor changes.

**Comment by filipesperandio** [comment]
Closing in favor of #24

**Pull request closed without merging**
